//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from RoboChartExpression.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace RoboChartInterpreter.Expressions {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class RoboChartExpressionLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, INT=11, REAL=12, NAME=13, STRING=14, WS=15;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "INT", "REAL", "NAME", "STRING", "WS"
	};


	public RoboChartExpressionLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public RoboChartExpressionLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'*'", "'/'", "'+'", "'-'", "'>'", "'>='", "'<'", "'<='", "'=='", 
		"'!='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, "INT", 
		"REAL", "NAME", "STRING", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "RoboChartExpression.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static RoboChartExpressionLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,15,95,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,
		14,1,0,1,0,1,1,1,1,1,2,1,2,1,3,1,3,1,4,1,4,1,5,1,5,1,5,1,6,1,6,1,7,1,7,
		1,7,1,8,1,8,1,8,1,9,1,9,1,9,1,10,4,10,57,8,10,11,10,12,10,58,1,11,4,11,
		62,8,11,11,11,12,11,63,1,11,1,11,5,11,68,8,11,10,11,12,11,71,9,11,1,12,
		1,12,5,12,75,8,12,10,12,12,12,78,9,12,1,13,1,13,5,13,82,8,13,10,13,12,
		13,85,9,13,1,13,1,13,1,14,4,14,90,8,14,11,14,12,14,91,1,14,1,14,0,0,15,
		1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,8,17,9,19,10,21,11,23,12,25,13,27,14,
		29,15,1,0,5,1,0,48,57,3,0,65,90,95,95,97,122,4,0,48,57,65,90,95,95,97,
		122,3,0,10,10,13,13,34,34,3,0,9,10,12,13,32,32,100,0,1,1,0,0,0,0,3,1,0,
		0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,
		1,0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,0,21,1,0,0,0,0,23,1,0,0,0,0,25,1,0,0,
		0,0,27,1,0,0,0,0,29,1,0,0,0,1,31,1,0,0,0,3,33,1,0,0,0,5,35,1,0,0,0,7,37,
		1,0,0,0,9,39,1,0,0,0,11,41,1,0,0,0,13,44,1,0,0,0,15,46,1,0,0,0,17,49,1,
		0,0,0,19,52,1,0,0,0,21,56,1,0,0,0,23,61,1,0,0,0,25,72,1,0,0,0,27,79,1,
		0,0,0,29,89,1,0,0,0,31,32,5,42,0,0,32,2,1,0,0,0,33,34,5,47,0,0,34,4,1,
		0,0,0,35,36,5,43,0,0,36,6,1,0,0,0,37,38,5,45,0,0,38,8,1,0,0,0,39,40,5,
		62,0,0,40,10,1,0,0,0,41,42,5,62,0,0,42,43,5,61,0,0,43,12,1,0,0,0,44,45,
		5,60,0,0,45,14,1,0,0,0,46,47,5,60,0,0,47,48,5,61,0,0,48,16,1,0,0,0,49,
		50,5,61,0,0,50,51,5,61,0,0,51,18,1,0,0,0,52,53,5,33,0,0,53,54,5,61,0,0,
		54,20,1,0,0,0,55,57,7,0,0,0,56,55,1,0,0,0,57,58,1,0,0,0,58,56,1,0,0,0,
		58,59,1,0,0,0,59,22,1,0,0,0,60,62,7,0,0,0,61,60,1,0,0,0,62,63,1,0,0,0,
		63,61,1,0,0,0,63,64,1,0,0,0,64,65,1,0,0,0,65,69,5,46,0,0,66,68,7,0,0,0,
		67,66,1,0,0,0,68,71,1,0,0,0,69,67,1,0,0,0,69,70,1,0,0,0,70,24,1,0,0,0,
		71,69,1,0,0,0,72,76,7,1,0,0,73,75,7,2,0,0,74,73,1,0,0,0,75,78,1,0,0,0,
		76,74,1,0,0,0,76,77,1,0,0,0,77,26,1,0,0,0,78,76,1,0,0,0,79,83,5,34,0,0,
		80,82,8,3,0,0,81,80,1,0,0,0,82,85,1,0,0,0,83,81,1,0,0,0,83,84,1,0,0,0,
		84,86,1,0,0,0,85,83,1,0,0,0,86,87,5,34,0,0,87,28,1,0,0,0,88,90,7,4,0,0,
		89,88,1,0,0,0,90,91,1,0,0,0,91,89,1,0,0,0,91,92,1,0,0,0,92,93,1,0,0,0,
		93,94,6,14,0,0,94,30,1,0,0,0,7,0,58,63,69,76,83,91,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace RoboChartInterpreter.Expressions
