//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from RoboChartExpression.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace RoboChartInterpreter.Expressions {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class RoboChartExpressionLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, INT=3, REAL=4, NAME=5, STRING=6, WS=7;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "INT", "REAL", "NAME", "STRING", "WS"
	};


	public RoboChartExpressionLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public RoboChartExpressionLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'=='", "'!='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, "INT", "REAL", "NAME", "STRING", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "RoboChartExpression.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static RoboChartExpressionLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,7,61,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		1,0,1,0,1,0,1,1,1,1,1,1,1,2,4,2,23,8,2,11,2,12,2,24,1,3,4,3,28,8,3,11,
		3,12,3,29,1,3,1,3,5,3,34,8,3,10,3,12,3,37,9,3,1,4,1,4,5,4,41,8,4,10,4,
		12,4,44,9,4,1,5,1,5,5,5,48,8,5,10,5,12,5,51,9,5,1,5,1,5,1,6,4,6,56,8,6,
		11,6,12,6,57,1,6,1,6,0,0,7,1,1,3,2,5,3,7,4,9,5,11,6,13,7,1,0,5,1,0,48,
		57,3,0,65,90,95,95,97,122,4,0,48,57,65,90,95,95,97,122,3,0,10,10,13,13,
		34,34,3,0,9,10,12,13,32,32,66,0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,
		1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,1,15,1,0,0,0,3,18,1,0,0,
		0,5,22,1,0,0,0,7,27,1,0,0,0,9,38,1,0,0,0,11,45,1,0,0,0,13,55,1,0,0,0,15,
		16,5,61,0,0,16,17,5,61,0,0,17,2,1,0,0,0,18,19,5,33,0,0,19,20,5,61,0,0,
		20,4,1,0,0,0,21,23,7,0,0,0,22,21,1,0,0,0,23,24,1,0,0,0,24,22,1,0,0,0,24,
		25,1,0,0,0,25,6,1,0,0,0,26,28,7,0,0,0,27,26,1,0,0,0,28,29,1,0,0,0,29,27,
		1,0,0,0,29,30,1,0,0,0,30,31,1,0,0,0,31,35,5,46,0,0,32,34,7,0,0,0,33,32,
		1,0,0,0,34,37,1,0,0,0,35,33,1,0,0,0,35,36,1,0,0,0,36,8,1,0,0,0,37,35,1,
		0,0,0,38,42,7,1,0,0,39,41,7,2,0,0,40,39,1,0,0,0,41,44,1,0,0,0,42,40,1,
		0,0,0,42,43,1,0,0,0,43,10,1,0,0,0,44,42,1,0,0,0,45,49,5,34,0,0,46,48,8,
		3,0,0,47,46,1,0,0,0,48,51,1,0,0,0,49,47,1,0,0,0,49,50,1,0,0,0,50,52,1,
		0,0,0,51,49,1,0,0,0,52,53,5,34,0,0,53,12,1,0,0,0,54,56,7,4,0,0,55,54,1,
		0,0,0,56,57,1,0,0,0,57,55,1,0,0,0,57,58,1,0,0,0,58,59,1,0,0,0,59,60,6,
		6,0,0,60,14,1,0,0,0,7,0,24,29,35,42,49,57,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace RoboChartInterpreter.Expressions
